deploy:
  provider: s3
  access_key_id: AKIAIEA25JB2OB2U6XSQ
  secret_access_key:
    secure: VuFsDulj5y38TzIUKYtrwBV6sGE+J9yHX5G7qqiG0Bn0/mBy2ZHB4t6oNW88qaLc9mdBXN013tP623tyLDn2ZqrDWB6NPANvoaXQlAMkMjd46EcT434IbQfXGOQpSXZ3z8sFma3dejTNA14sCE0orzwQNEnBK9qLZdhGDIsZWiuMzmdqWWVcVsT3/DpMYKnb0V4xT8CUmq5M2xvcDbVEA2fqO9y9ZaqLmZN9d3hwR41EcoLw/4uuamDFov7hGf5xD7epIpTZjCZWsoi3CG3FbfFgIOOI/wHJ2ziEjywCE/OVlgvpdbnd330cTLu8XxfmG8xigV/F4aX1q0gq8NtrYTTsFijxy2FUG3wFklihmvOc9NUrovbQ2t9Vy/ti/L3SyhveJlgWUKfY3HYukeuwQINHttMHpk0thiDY1HPpvLTCHWsqIs5vkzxnpYmtHQ/vsfuEjcma3FgGWHNZ80AU0fYvpQjHzb6UF99Ab0y/GoQZzH2H1CHwWr9g6BKByIqNitsBzfl7VNk1EP63zx9gR+DPFaep0D8pw3TUzw9/MUSum+B836h+hA9WVSS9mqZDY1ocLcLAr3bDrTTFX9z8GBnsCxVjrR0BL2fdqhw9oBoV55KWh06kD77p2liw3mGP5a2+T+buT0Ij+3HRhrHAfFYz2DF/I5C0wXwccW01xMs=
  bucket: brom.horse
  acl: public_read 
  s3_host_name: s3-us-west-1.amazonaws.com
language: node_js
node_js:
  - node