language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAIEA25JB2OB2U6XSQ
  secret_access_key:
    secure: m2CaTnwfhVCfDrFUm57ouQXShIcm4k/pzwfJPiLN59DPMNN6t7a/+a+5DyKx0FkHSLTKmlou0aJig6q01W5uNV8nDFC+DMYZRqwx89keBnSK1Y5RIuORUzcVeQQcLohJU2mvXq5FavOjeKi9OcRYPwAoD3POfibfaCcj6uRw/6NVOl9U4EhB/5pqz4YpxkAEdsnnXxEBF2cUxVNB7jnLdn9T47lGXxExYL5TANWvmRL/ma0FRhyBFe2OZ4oRU6h80+wBdym1U2YPitN7OL43jQqqIx3NEocOfRvEYBfKaMkM89qTpsJ7LOT7xx9gzTMefdJGD8ET2OqJPTeCtxfeZFUD8+XeVvF1B7cZI41hbYR6jHX5S6tRruYKulsaJzbQ6QwgPSDhcAYah6QsACfpdnHxZeKqHEZK44nIwHGnKJWWpOyCBQn0m2jSGp/6/Mj7yCfzx8tNKgIt5ZqHbFl7PPnnK5lC+Z3I2WGNDJjnu89DXvOnl77iTC264Uq/TDeiwXV9ixyZuNAo/l4ZmlTv/cNnJSBR/+VpL3KS4s3lKR0yRretJSEGhjYkD1XCCYcFOqKlL1jac783D/R1MKbkBvtrKI+LaznpNsUBHSR2d4ql5p/LcJqbsQG9RuwJi03nD5cHnpX5/J5v6BnjZeXXptcxCmy2eprN/1fI3vsn5hU=
  bucket: brom.horse
  skip_cleanup: true
  region: eu-west-1
