language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAIEA25JB2OB2U6XSQ
  secret_access_key:
    secure: iHwD1Q/2R0l9LJtFDKlSxKzCI6ZFWcQSSeXtfmTgJD2QJ8VL/bvjjnHot5U/SciGXVDmyVdPesRAPLa0s1stUW0xhkr55WtUu530djKuwxV/Zt+hATD28jA01I+omJ6aKI+NbDXP3y31deNUk7m50vh+iwZ1VfY0kXvOVLO0Yi9YzMN8jTM9nod49zNawDQxcPT85G5aVwMzLc0Iz3u21JT5HAAbkHH37nrN4Y0VVcQQHC3GjIJ77gyn8+f5phPogPK/UF+lDzA5Mpi4ljONUh/meNs0hmHnSt9g/e29fHntQ/ge1+25ra3pDncENdzky1N5zvQxCSOwcrR23FIKksLc+mBbBV035ocBTLmUKG8ph1184g3+by5xm/s9NuBKOD0E7zTYazS8B7FpRWR2Vm7Ami4hsgC6lEY5tUS6SxZIfhUKoO8FlIJ3Ju6hRPxdtgwAjTDrEX0G1ARu+DvUfKMScm7hwPFV6m/BoOwxKsbbjk4srJ443DM76rtKvNMCKgaH+qQotk/f1alHtV73kbhA1oV2D7YYAfP2pRuviY86UAiZ4WUmD4OwQtfwfqd+UzITt+aEC1oNDSEHCpL3BD/TahLewXRHrbLAFMSMV+343wgLJ83ALBZgG2NQtIvPXFhx5mvZ/pw6kF2B4rSHaRGRmOTUVEVHfkcK2lDHEmI=
  bucket: brom.horse
  acl: public_read
  region: us-west-1
