language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAIEA25JB2OB2U6XSQ
  secret_access_key:
    secure: O0NpzMlpVriSp8vbl6jrxIbSW6un6TnQag23R7oD5zriJFByPE9aadzUPciXEyEjb7/Webv0H2YR6ndlbqleLT6u2RGnv5/rvGnhov0At5M0ZJejgkN6oipAju9lX5MFbtq5wlonp0RSZuDh23fm2T4KDYhDmGm0O0WmYCrShr6ufdVeqWtfuvUtR7r46r5t1Pp51dcjJz2GJhOjLXa8O3yIf1VTfjbEBuraHfajIjGxN4uLyL4AgqyVTo8xYAXiyf3bOx2snSpP8EU3fzSF30Ww/94zfuqDAWPzfDJvVW/W+Jcymff/aWVTNY9NLHhU81lDBwE5O4HOoVQjpAK6eZuupa54aMJ4XnKyZfKFiIhI8fTQoOTwmEKJhoJganG5lGHdjzQ6ul3UxY1KVlSlvFww5BLofV6aO/GZc7d2YTs27F378rFivzfUQhpflz8PsMqNoBdJT6fiV4L6fn8+C5mPlv7QonS/5j1P8SHBUgyQHsna4j3tzIhj5HAJL5Ye40e3go6iK0viO8/gh9yqUaPzmZ4zRxh0oxCeHjuz2ybDMERpJlTieePjeAyxcpIEGjpv9Bo09EZEGAM8mIWhiShqP/MIVlAwBxow32gLTryJRegg5tsKXDrI5se5jWbupJBJEfFP7gd+Km4okq8yh9F+nE6s5BvvmsIvfdXtFQ0=
  bucket: www.brom.horse
  acl: public_read
  region: us-west-1
